### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by brandonhudson**
Added branding and colors to make it look like a CSH service

### CODE REVIEW

**Comment by bencentra** [comment]
Cool! Only noticed one problem with the CSS: 

navbar1

Are these "branding" changes gonna get folded back into [bootstrap-csh](https://github.com/bencentra/bootstrap-csh)? Is there anything I can do to make doing that easier? (Adding contributors, moving the repo under CSH, etc)

**Comment by bencentra** [comment]
Your changes are being hosted here: https://members.csh.rit.edu/~bencentra/webdrink-dev

**Comment by brandonhudson** [comment]
Oh haha sorry, Ill get that fixed tonight! Didnt even think to modify the
:focus on the dropdown.

**Comment by brandonhudson** [comment]
To respond to the first question I didn't see, yes, I intend to release a branch on bootstrap-csh for flat design (both purple and pink). I may just do it in SCSS and let people change out a variable between the two colors - haven't decided yet.

**Comment by brandonhudson** [comment]
I made a PR on the bootstrap-csh repo, adding flat UI options for both purple and pink. I integrated that into this project and added a dynamic theme switcher to allow users to select the theme they prefer. It stores that preference in localStorage using ngStorage. Everything minus the dom manipulation function is written in angular inside the app.js and settings.js scripts.

**Comment by bencentra** [comment]
Don't know why you need a theme switcher, but it's cool! 

I noticed two more CSS things, probably introduced by members-flat.css:

First, links within Alerts (and probably other components with custom backgrounds) don't change color to match the context. This may have been an existing bug, I'm not sure. 

screen shot 2016-01-17 at 8 16 17 pm

Second, with the Pink theme selected the Primary and Secondary colors are the same. Here's an example (it's seen throughout the app):

screen shot 2016-01-17 at 8 19 47 pm

**Comment by brandonhudson** [comment]
Ill work on this over the week/next weekend.

**Comment by brandonhudson** [comment]
Should be all set

**Comment by brandonhudson** [comment]
Ping

**Comment by bencentra** [comment]
:+1:

**Pull request merged**
